#!/bin/bash

if [ "$1" = "connect" ]; then
	ssh -L $2:localhost:$2 $3 $*
elif [ "$1" = "serve" ]; then
	ssh -R $2:localhost:$2 $3 $*
else
	echo "Usage: piper [connect|serve] <port> <remote-host> [openssh-args]"
fi




